runtime: nodejs18

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  HOST: "0.0.0.0"
  USE_MOCK_DATA: "false"
  GCS_BUCKET_NAME: "giselle-uploads"

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 300ms
  max_concurrent_requests: 80 